services:
  - type: web
    name: nacho-helpdesk
    runtime: python
    buildCommand: pip install -r requirements.txt && python database/init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true